;
(function ($) {
    'use strict';
    $.mockjax({
        url: '/top100',
        type: 'post',
        contentType: 'text/json',
        dataType: 'json',
        responseText: [
            {title: "Adventures of Huckleberry Finn", author: "Mark Twain", year: "1901"},
            {title: "Pride and Prejudice", author: "Jane Austen", year: "1293"},
            {title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle", year: "1279"},
            {title: "Les Misérables", author: "Victor Hugo", year: "1098"},
            {title: "Alice's Adventures in Wonderland", author: "Lewis Carroll", year: "907"},
            {title: "Grimms' Fairy Tales", author: "Jacob Grimm and Wilhelm Grimm", year: "690"},
            {title: "The Kama Sutra of Vatsyayana", author: "Vatsyayana", year: "686"},
            {title: "The Prince", author: "Niccolò Machiavelli", year: "656"},
            {title: "How to Analyze People on Sight", author: "Elsie Lincoln Benedict and Ralph Paine Benedict", year: "614"},
            {title: "The Adventures of Tom Sawyer", author: "Mark Twain", year: "594"},
            {title: "Wuthering Heights", author: "Emily Brontë", year: "586"},
            {title: "The Importance of Being Earnest: A Trivial Comedy for Serious People", author: "Oscar Wilde", year: "542"},
            {title: "A Christmas Carol in Prose; Being a Ghost Story of Christmas", author: "Charles Dickens", year: "538"},
            {title: "Metamorphosis", author: "Franz Kafka", year: "502"},
            {title: "Moby Dick; Or, The Whale", author: "Herman Melville", year: "500"},
            {title: "A Tale of Two Cities", author: "Charles Dickens", year: "492"},
            {title: "Frankenstein; Or, The Modern Prometheus", author: "Mary Wollstonecraft Shelley", year: "477"},
            {title: "Ulysses", author: "James Joyce", year: "462"},
            {title: "The Oxford Book of Ballads", author: "Various", year: "455"},
            {title: "Great Expectations", author: "Charles Dickens", year: "447"},
            {title: "A Study in Scarlet", author: "Arthur Conan Doyle", year: "432"},
            {title: "Martha of California", author: "James Otis", year: "420"},
            {title: "The Divine Comedy", author: "Dante Alighieri", year: "418"},
            {title: "Peter Pan", author: "J. M. Barrie", year: "415"},
            {title: "Leaves of Grass", author: "Walt Whitman", year: "404"},
            {title: "Beowulf", year: "364"},
            {title: "The Count of Monte Cristo", author: "Alexandre Dumas", year: "357"},
            {title: "Beyond the Marne", author: "Henriette Cuvru-Magot", year: "349"},
            {title: "Sunzi bing fa. English", author: "active 6th century B.C. Sunzi", year: "345"},
            {title: "Dracula", author: "Bram Stoker", year: "334"},
            {title: "L'Illustration, No. 2506, 7 Mars 1891", author: "Various", year: "334"},
            {title: "The Picture of Dorian Gray", author: "Oscar Wilde", year: "327"},
            {title: "Siddhartha", author: "Hermann Hesse", year: "327"},
            {title: "Gulliver's Travels", author: "Jonathan Swift", year: "319"},
            {title: "The Complete Works of William Shakespeare", author: "William Shakespeare", year: "317"},
            {title: "Dubliners", author: "James Joyce", year: "310"},
            {title: "War and Peace", author: "graf Leo Tolstoy", year: "308"},
            {title: "A Tale of Two Tunnels", author: "William Clark Russell", year: "308"},
            {title: "Jane Eyre: An Autobiography", author: "Charlotte Brontë", year: "303"},
            {title: "Emma", author: "Jane Austen", year: "290"},
            {title: "A Doll's House : a play", author: "Henrik Ibsen", year: "285"},
            {title: "Heart of Darkness", author: "Joseph Conrad", year: "282"},
            {title: "Roughing It", author: "Mark Twain", year: "280"},
            {title: "The Little Maid of Israel", author: "Emma Howard Wight", year: "275"},
            {title: "The Republic", author: "Plato", year: "272"},
            {title: "Narrative of the Life of Frederick Douglass, an American Slave", author: "Frederick Douglass", year: "270"},
            {title: "The King James Version of the Bible", year: "263"},
            {title: "The Return of Sherlock Holmes", author: "Arthur Conan Doyle", year: "262"},
            {title: "Light for Little Ones", author: "Mary F. Waterbury", year: "256"},
            {title: "An Inquiry into the Nature and Causes of the Wealth of Nations", author: "Adam Smith", year: "256"},
            {title: "The Romance of Lust", author: "Anonymous", year: "255"},
            {title: "The Mysterious Affair at Styles", author: "Agatha Christie", year: "250"},
            {title: "Explanatory Notes of a Pack of Playing Cards, Temp Charles II.", author: "Edmund Goldsmid", year: "250"},
            {title: "A Connecticut Yankee in King Arthur's Court", author: "Mark Twain", year: "236"},
            {title: "How to Become an Engineer", author: "Frank W. Doughty", year: "233"},
            {title: "The Wonderful Wizard of Oz", author: "L. Frank Baum", year: "231"},
            {title: "Tractatus Logico-Philosophicus", author: "Ludwig Wittgenstein", year: "228"},
            {title: "The Call of the Wild", author: "Jack London", year: "224"},
            {title: "The Sign of the Four", author: "Arthur Conan Doyle", year: "223"},
            {title: "The Jungle Book", author: "Rudyard Kipling", year: "223"},
            {title: "Beyond Good and Evil", author: "Friedrich Wilhelm Nietzsche", year: "220"},
            {title: "Sense and Sensibility", author: "Jane Austen", year: "212"},
            {title: "The Innocents Abroad", author: "Mark Twain", year: "212"},
            {title: "A Princess of Mars", author: "Edgar Rice Burroughs", year: "210"},
            {title: "The Hound of the Baskervilles", author: "Arthur Conan Doyle", year: "209"},
            {title: "The Prince and the Pauper", author: "Mark Twain", year: "205"},
            {title: "Three Men in a Boat", author: "Jerome K. Jerome", year: "202"},
            {title: "Anna Karenina", author: "graf Leo Tolstoy", year: "200"},
            {title: "The Brothers Karamazov", author: "Fyodor Dostoyevsky", year: "195"},
            {title: "The Strange Case of Dr. Jekyll and Mr. Hyde", author: "Robert Louis Stevenson", year: "193"},
            {title: "The Iliad", author: "Homer", year: "192"},
            {title: "Treasure Island", author: "Robert Louis Stevenson", year: "190"},
            {title: "Wood Engraving", author: "R. John Beedham", year: "190"},
            {title: "Andersen's Fairy Tales", author: "H. C. Andersen", year: "189"},
            {title: "The Secret Adversary", author: "Agatha Christie", year: "188"},
            {title: "A Tramp Abroad", author: "Mark Twain", year: "185"},
            {title: "The Yellow Wallpaper", author: "Charlotte Perkins Gilman", year: "185"},
            {title: "David Copperfield", author: "Charles Dickens", year: "182"},
            {title: "Life on the Mississippi", author: "Mark Twain", year: "181"},
            {title: "Ein Blick in die Zukunft", author: "Richard Michaelis", year: "179"},
            {title: "The Memoirs of Sherlock Holmes", author: "Arthur Conan Doyle", year: "179"},
            {title: "The Divine Comedy", author: "Dante Alighieri", year: "179"},
            {title: "The Works of Edgar Allan Poe — Volume 1", author: "Edgar Allan Poe", year: "178"},
            {title: "The Awakening, and Selected Short Stories", author: "Kate Chopin", year: "176"},
            {title: "Madame Bovary", author: "Gustave Flaubert", year: "175"},
            {title: "Walden, and On The Duty Of Civil Disobedience", author: "Henry David Thoreau", year: "174"},
            {title: "Prestuplenie i nakazanie. English", author: "Fyodor Dostoyevsky", year: "174"},
            {title: "The Time Machine", author: "H. G. Wells", year: "173"},
            {title: "Oliver Twist", author: "Charles Dickens", year: "172"},
            {title: "Following the Equator: A Journey Around the World", author: "Mark Twain", year: "171"},
            {title: "Aesop's Fables; a new translation", author: "Aesop", year: "166"},
            {title: "The Life and Adventures of Robinson Crusoe", author: "Daniel Defoe", year: "165"},
            {title: "Steam, Its Generation and Use", author: "Babcock & Wilcox Company", year: "162"},
            {title: "The Turn of the Screw", author: "Henry James", year: "156"},
            {title: "Leviathan", author: "Thomas Hobbes", year: "156"},
            {title: "The War of the Worlds", author: "H. G. Wells", year: "155"},
            {title: "Josefine Mutzenbacher", author: "Felix Salten", year: "155"},
            {title: "Encyclopedia of Needlework", author: "Thérèse de Dillmont", year: "155"},
            {title: "The Knickerbocker, or The New-York Monthly Magazine, December 1843", author: "Various", year: "154"},
            {title: "Principles of Orchestration", author: "Nikolay Rimsky-Korsakov", year: "153"}
        ]
    });
    $.mockjax({
        url: '/slider',
        type: 'post',
        contentType: 'text/json',
        dataType: 'json',
        responseText: []
    });
})(jQuery);
